//! First-party in-memory `Org` workspace backend.

mod memory;

pub use memory::{
    MemoryOrgWorkspace, PROJECT_MEMORY_CONTENT_ID_PROPERTY,
    PROJECT_MEMORY_CONTRACT_VALIDATED_PROPERTY, PROJECT_MEMORY_ID_PROPERTY,
    PROJECT_MEMORY_PROJECT_ID_PROPERTY, PROJECT_MEMORY_RECALL_QUERY_PROPERTY,
    PROJECT_MEMORY_ROOT_SESSION_ID_PROPERTY, PROJECT_MEMORY_SESSION_ID_PROPERTY,
    PROJECT_MEMORY_WORKSPACE_ID_PROPERTY, PROJECT_MEMORY_WORKTREE_ID_PROPERTY,
};
