//! In-memory Org workspace backend for protocol tests and local agents.

mod content_graph;
mod contracts;
mod format;
mod patch;
mod project_graph;
mod query;
mod render;
mod session_graph;
mod status;
mod tool_graph;
mod workspace;

pub use content_graph::{
    CONTENT_NODE_AGENT_ID_PROPERTY, CONTENT_NODE_BODY_REF_PROPERTY,
    CONTENT_NODE_COMPRESSION_STATE_PROPERTY, CONTENT_NODE_CONTENT_ID_PROPERTY,
    CONTENT_NODE_CONTRACT_VALIDATED_PROPERTY, CONTENT_NODE_FORKED_FROM_CONTENT_ID_PROPERTY,
    CONTENT_NODE_PARENT_CONTENT_ID_PROPERTY, CONTENT_NODE_PROJECT_ID_PROPERTY,
    CONTENT_NODE_ROLE_PROPERTY, CONTENT_NODE_ROOT_SESSION_ID_PROPERTY,
    CONTENT_NODE_SESSION_ID_PROPERTY, CONTENT_NODE_TOKEN_COUNT_PROPERTY,
    CONTENT_NODE_WORKSPACE_ID_PROPERTY, CONTENT_NODE_WORKTREE_ID_PROPERTY,
};
pub use project_graph::{
    PROJECT_MEMORY_CONTENT_ID_PROPERTY, PROJECT_MEMORY_CONTRACT_VALIDATED_PROPERTY,
    PROJECT_MEMORY_ID_PROPERTY, PROJECT_MEMORY_PROJECT_ID_PROPERTY,
    PROJECT_MEMORY_RECALL_QUERY_PROPERTY, PROJECT_MEMORY_ROOT_SESSION_ID_PROPERTY,
    PROJECT_MEMORY_SESSION_ID_PROPERTY, PROJECT_MEMORY_WORKSPACE_ID_PROPERTY,
    PROJECT_MEMORY_WORKTREE_ID_PROPERTY,
};
pub use session_graph::{
    SESSION_FACT_AGENT_ID_PROPERTY, SESSION_FACT_CONTEXT_PACK_ID_PROPERTY,
    SESSION_FACT_CONTRACT_VALIDATED_PROPERTY, SESSION_FACT_FORKED_FROM_CONTENT_ID_PROPERTY,
    SESSION_FACT_HISTORY_LIMIT_PROPERTY, SESSION_FACT_KIND_PROPERTY,
    SESSION_FACT_PARENT_SESSION_ID_PROPERTY, SESSION_FACT_PROJECT_ID_PROPERTY,
    SESSION_FACT_ROOT_SESSION_ID_PROPERTY, SESSION_FACT_SESSION_ID_PROPERTY,
    SESSION_FACT_WORKSPACE_ID_PROPERTY, SESSION_FACT_WORKTREE_ID_PROPERTY,
};
pub use tool_graph::{
    TOOL_CAPABILITY_CONTRACT_VALIDATED_PROPERTY, TOOL_CAPABILITY_ID_PROPERTY,
    TOOL_CAPABILITY_PROJECT_ID_PROPERTY, TOOL_CAPABILITY_REQUIRED_RECEIPTS_PROPERTY,
    TOOL_CAPABILITY_ROOT_SESSION_ID_PROPERTY, TOOL_CAPABILITY_SESSION_ID_PROPERTY,
    TOOL_CAPABILITY_WORKSPACE_ID_PROPERTY, TOOL_CAPABILITY_WORKTREE_ID_PROPERTY,
};
pub use workspace::{
    MemoryOrgWorkspace, ProjectMemoryGraphStoreQuery, ProjectMemoryStoreRecall,
    ToolCapabilityGraphStoreQuery,
};
