;;; -*- Gerbil -*-
;;; Boundary: Marlin policy facade over the poo-flow module system.

package: config-interface/modules

(import :config-interface/modules/kinds
        :config-interface/modules/policy-extension
        :config-interface/modules/policy-module
        :config-interface/modules/policy-object
        :config-interface/modules/workspace-policy
        :config-interface/modules/session-policy
        :config-interface/modules/agent-policy
        :config-interface/modules/hook-selection-policy
        :config-interface/modules/model-route-policy
        :config-interface/modules/continuation-profile-policy
        :config-interface/modules/loop-engine-policy
        :config-interface/modules/human-review-policy
        :config-interface/modules/evidence-policy
        :config-interface/modules/failure-policy
        :config-interface/modules/memory-policy
        :config-interface/modules/domain-policy
        :config-interface/modules/catalog-projection-policy
        :config-interface/modules/evaluation
        :config-interface/modules/policy-pack)

(export marlin-config-interface-kind
        marlin-module-workflow-kind
        marlin-module-catalog-kind
        marlin-eval-modules-result-kind
        marlin-policy-facade-presentation-kind
        marlin-module-projection-chain-kind
        marlin-policy-extension-kind
        marlin-policy-module-kind
        marlin-policy-module-workflow-kind
        marlin-policy-substrate-gate-kind
        marlin-policy-pack-kind
        marlin-pack-catalog-kind
        marlin-pack-catalog-presentation-kind
        marlin-policy-projection-chain-receipt-kind
        marlin-policy-budget-receipt-kind
        marlin-policy-catalog-resolution-receipt-kind
        marlin-policy-projection-kind
        marlin-poo-loop-program-compiler-receipt-kind
        marlin-policy-pack-presentation-kind
        marlin-policy-pack-inventory-kind
        marlin-policy-object-kind
        marlin-policy-object-operation-kind
        marlin-policy-object-surgery-receipt-kind
        marlin-module-import-kind
        marlin-import-source-ref-kind
        marlin-import-local-source-kind
        marlinPolicyExtension
        defmarlin-policy-extension
        marlinPolicyModule
        defmarlin-policy-module
        marlinPolicyObject
        marlin-policy-object?
        marlin-policy-object-id
        marlin-policy-object-family
        marlin-policy-object-ids
        marlin-policy-object-families
        marlin-policy-object-disabled-ids
        marlin-add-object
        marlin-remove-object
        marlin-disable-object
        marlin-replace-object
        marlin-policy-object-operation?
        marlin-policy-pack-apply-operations
        marlin-workspace-policy-family
        marlinWorkspacePolicy
        marlinDefaultWorkspacePolicy
        marlin-session-policy-family
        marlinSessionPolicy
        marlinDefaultSessionPolicy
        marlin-agent-policy-family
        marlinAgentPolicy
        marlinDefaultAgentPolicy
        marlin-hook-selection-policy-family
        marlinHookSelectionPolicy
        marlinDefaultHookSelectionPolicy
        marlin-model-route-policy-family
        marlinModelRoutePolicy
        marlinDefaultModelRoutePolicy
        marlin-continuation-profile-policy-family
        marlin-continuation-profile-family
        marlinContinuationProfilePolicy
        marlinContinuationProfile
        marlinDefaultContinuationProfilePolicy
        marlin-loop-engine-policy-family
        marlinDefaultLoopEngineReceiptContracts
        marlinLoopEnginePolicy
        marlinDefaultLoopEnginePolicy
        marlin-human-review-policy-family
        marlinHumanReviewPolicy
        marlinDefaultHumanReviewPolicy
        marlin-evidence-graph-policy-family
        marlinEvidenceGraphPolicy
        marlinDefaultEvidenceGraphPolicy
        marlin-failure-recovery-policy-family
        marlinFailureRecoveryPolicy
        marlinDefaultFailureRecoveryPolicy
        marlin-memory-recall-policy-family
        marlin-memory-trigger-policy-family
        marlin-memory-retention-policy-family
        marlin-memory-visibility-policy-family
        marlinMemoryRecallPolicy
        marlinMemoryTriggerPolicy
        marlinMemoryRetentionPolicy
        marlinMemoryVisibilityPolicy
        marlinDefaultMemoryRecallPolicy
        marlinDefaultMemoryTriggerPolicy
        marlinDefaultMemoryRetentionPolicy
        marlinDefaultMemoryVisibilityPolicy
        marlin-subagent-policy-family
        marlin-context-compression-policy-family
        marlin-tool-batch-policy-family
        marlin-self-evolution-policy-family
        marlinSubagentPolicy
        marlinContextCompressionPolicy
        marlinToolBatchPolicy
        marlinSelfEvolutionPolicy
        marlinDefaultSubagentPolicy
        marlinDefaultContextCompressionPolicy
        marlinDefaultToolBatchPolicy
        marlinDefaultSelfEvolutionPolicy
        marlin-catalog-projection-policy-family
        marlinCatalogProjectionPolicy
        marlinDefaultCatalogProjectionPolicy
        marlinPolicyPack
        defmarlin-policy-pack
        marlinDefaultPolicyPack
        marlinPackCatalog
        marlin-pack-catalog-find
        marlin-pack-catalog-root
        marlinPackCatalogPresentation
        marlinPolicyPackInventory
        marlinPolicyPackPresentation
        marlinPolicyProjection
        marlinPooLoopProgramCompilerReceipt
        marlin-policy-slot-merge-receipt-kind
        marlin-policy-slot-merge-algebra-demo-receipt-kind
        marlinPolicySlotMergeReceipt
        marlinPolicySlotMergeUnion
        marlinPolicySlotMergeIntersection
        marlinPolicySlotMergeMin
        marlinPolicySlotMergeOrderedAppend
        marlinPolicySlotMergeConflictError
        marlinPolicySlotMergeAlgebraDemoReceipt
        marlinLoopPolicyProfileProjectionDescriptor
        marlinLoopPolicyProfileProjectionDescriptors
        marlinLoopVerticalMainlineProjectionDescriptors
        marlinLoopPolicyProjectionModuleFromDescriptor
        marlinLoopPolicyProjectionModules
        marlinLoopPolicyProfileCompilerReceipts
        marlinRealRepair001ResolvedPolicyPack
        marlinRealRepair001LoopProgram
        marlinRealRepair001LoopProgramCompilerReceipt
        marlinRealPolicy001SandboxDenylistResolvedPolicyPack
        marlinRealPolicy001SandboxDenylistLoopProgram
        marlinRealPolicy001SandboxDenylistLoopProgramCompilerReceipt
        marlinRealToolSandboxResolvedPolicyPack
        marlinRealToolSandboxLoopProgram
        marlinRealToolSandboxLoopProgramCompilerReceipt
        marlinFailureRetryResolvedPolicyPack
        marlinFailureRetryLoopProgram
        marlinFailureRetryLoopProgramCompilerReceipt
        marlinPolicyCombinationMatrixResolvedPolicyPack
        marlinPolicyCombinationMatrixLoopProgram
        marlinPolicyCombinationMatrixLoopProgramCompilerReceipt
        marlinPolicyModuleEvaluationReceipt
        marlinPolicyBudgetReceipt
        marlinPolicyCatalogResolutionReceipt
        marlinPolicyProjectionReceipts
        marlinPolicyProjectionChainReceipt
        marlin-policy-extension?
        marlin-policy-module?
        marlin-policy-extension-object-count
        marlin-policy-module-substrate-gate
        marlin-policy-module-workflow)
