;;; -*- Gerbil -*-
;;; Boundary: Public facade for the Gerbil POO module system.

package: modules

(import :modules/kinds
        :modules/core
        :modules/policy-extension
        :modules/policy-module
        :modules/policy-object
        :modules/workspace-policy
        :modules/session-policy
        :modules/agent-policy
        :modules/hook-selection-policy
        :modules/model-route-policy
        :modules/continuation-profile-policy
        :modules/human-review-policy
        :modules/evidence-policy
        :modules/failure-policy
        :modules/memory-policy
        :modules/catalog-projection-policy
        :modules/evaluation
        :modules/policy-pack)

(export marlin-modules-kind
        marlin-module-workflow-kind
        marlin-module-catalog-kind
        marlin-eval-modules-result-kind
        marlin-module-system-presentation-kind
        marlin-module-projection-chain-kind
        marlin-policy-extension-kind
        marlin-policy-module-kind
        marlin-policy-module-workflow-kind
        marlin-policy-substrate-gate-kind
        marlin-policy-pack-kind
        marlin-pack-catalog-kind
        marlin-pack-catalog-presentation-kind
        marlin-policy-projection-chain-receipt-kind
        marlin-policy-budget-receipt-kind
        marlin-policy-catalog-resolution-receipt-kind
        marlin-policy-projection-kind
        marlin-policy-pack-presentation-kind
        marlin-policy-pack-inventory-kind
        marlin-policy-object-kind
        marlin-policy-object-operation-kind
        marlin-policy-object-surgery-receipt-kind
        marlin-module-import-kind
        marlin-import-source-ref-kind
        marlin-import-local-source-kind
        marlinModules
        marlinPolicyExtension
        defmarlin-policy-extension
        marlinPolicyModule
        defmarlin-policy-module
        marlinPolicyObject
        marlin-policy-object?
        marlin-policy-object-id
        marlin-policy-object-family
        marlin-policy-object-ids
        marlin-policy-object-families
        marlin-policy-object-disabled-ids
        marlin-add-object
        marlin-remove-object
        marlin-disable-object
        marlin-replace-object
        marlin-policy-object-operation?
        marlin-policy-pack-apply-operations
        marlin-workspace-policy-family
        marlinWorkspacePolicy
        marlinDefaultWorkspacePolicy
        marlin-session-policy-family
        marlinSessionPolicy
        marlinDefaultSessionPolicy
        marlin-agent-policy-family
        marlinAgentPolicy
        marlinDefaultAgentPolicy
        marlin-hook-selection-policy-family
        marlinHookSelectionPolicy
        marlinDefaultHookSelectionPolicy
        marlin-model-route-policy-family
        marlinModelRoutePolicy
        marlinDefaultModelRoutePolicy
        marlin-continuation-profile-policy-family
        marlin-continuation-profile-family
        marlinContinuationProfilePolicy
        marlinContinuationProfile
        marlinDefaultContinuationProfilePolicy
        marlin-human-review-policy-family
        marlinHumanReviewPolicy
        marlinDefaultHumanReviewPolicy
        marlin-evidence-graph-policy-family
        marlinEvidenceGraphPolicy
        marlinDefaultEvidenceGraphPolicy
        marlin-failure-recovery-policy-family
        marlinFailureRecoveryPolicy
        marlinDefaultFailureRecoveryPolicy
        marlin-memory-trigger-policy-family
        marlinMemoryTriggerPolicy
        marlinDefaultMemoryTriggerPolicy
        marlin-catalog-projection-policy-family
        marlinCatalogProjectionPolicy
        marlinDefaultCatalogProjectionPolicy
        marlinPolicyPack
        defmarlin-policy-pack
        marlinDefaultPolicyPack
        marlinPackCatalog
        marlin-pack-catalog-find
        marlin-pack-catalog-root
        marlinPackCatalogPresentation
        marlinPolicyPackInventory
        marlinPolicyPackPresentation
        marlinPolicyProjection
        marlinPolicyProjectionChainReceipt
        marlinModuleCatalog
        marlin-import
        marlin-imports
        marlin-imports-append
        marlin-extensions
        marlin-extensions-append
        marlin-import?
        marlin-policy-extension?
        marlin-policy-module?
        marlin-module-import-source-ref?
        marlin-module-import-local-source?
        marlin-module-import-normalize-source
        marlin-source-ref
        marlin-local-source
        marlin-module-interface
        marlin-string-required
        marlin-string-constant
        marlin-string-default
        marlin-string-optional
        marlin-module-runtime-import
        marlin-module-option-configs
        marlin-module-option-schemas
        marlin-module-find-schema
        marlin-module-missing-schema-receipt
        marlin-module-option-validation-receipts
        marlin-module-validation-receipts
        marlin-module-apply
        marlin-module-evaluate
        marlin-module-workflow
        marlin-module-catalog-find
        marlin-module-catalog-root
        marlinEvalModules
        marlinModuleSystemPresentation
        marlin-policy-extension-object-count
        marlin-policy-module-substrate-gate
        marlin-policy-module-workflow)
